apiVersion: apps/v1
kind: Deployment
metadata:
  name: despachos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: despachos
  template:
    metadata:
      labels:
        app: despachos
    spec:
      containers:
        - name: despachos-container
          image: 220943776304.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-despachos:latest
          ports:
            - containerPort: 8091
          env:
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_ENDPOINT
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: despachos-service
spec:
  selector:
    app: despachos
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP